---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
    OrdererEndpoints:
      - orderer1.ictcog.or.kr:7050
      - orderer2.ictcog.or.kr:7050
      - orderer3.ictcog.or.kr:7050

  - &DaeguOrg
    Name: DaeguMSP
    ID: DaeguMSP
    MSPDir: ../cryptogen/crypto-config/peerOrganizations/daegu.ictcog.or.kr/msp
    Policies: &DaeguOrgPolicies
      Readers:
        Type: Signature
        Rule: "OR('DaeguMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DaeguMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('DaeguMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('DaeguMSP.member')"
    AnchorPeers:
      - Host: peer0.daegu.ictcog.or.kr
        Port: 7051
      - Host: peer1.daegu.ictcog.or.kr
        Port: 17051

  - &PohangOrg
    Name: PohangMSP
    ID: PohangMSP
    MSPDir: ../cryptogen/crypto-config/peerOrganizations/pohang.ictcog.or.kr/msp
    Policies: &PohangOrgPolicies
      Readers:
        Type: Signature
        Rule: "OR('PohangMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('PohangMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('PohangMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('PohangMSP.member')"
    AnchorPeers:
      - Host: peer0.pohang.ictcog.or.kr
        Port: 9051
      - Host: peer1.pohang.ictcog.or.kr
        Port: 19051
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer1.ictcog.or.kr:7050
    - orderer2.ictcog.or.kr:7050
    - orderer3.ictcog.or.kr:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ict-channel-a:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer1.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer1.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer1.ictcog.or.kr/tls/server.crt
          - Host: orderer2.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer2.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer2.ictcog.or.kr/tls/server.crt
          - Host: orderer3.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer3.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer3.ictcog.or.kr/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *DaeguOrg
        - *PohangOrg
      Capabilities: *ApplicationCapabilities

  ict-channel-b:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer1.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer1.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer1.ictcog.or.kr/tls/server.crt
          - Host: orderer2.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer2.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer2.ictcog.or.kr/tls/server.crt
          - Host: orderer3.ictcog.or.kr
            Port: 7050
            ClientTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer3.ictcog.or.kr/tls/server.crt
            ServerTLSCert: ../cryptogen/crypto-config/ordererOrganizations/ictcog.or.kr/orderers/orderer3.ictcog.or.kr/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *DaeguOrg
        - *PohangOrg
      Capabilities: *ApplicationCapabilities
