NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ictcog.or.kr-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ictcog.or.kr-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.ictcog.or.kr-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.ictcog.or.kr-cert.pem
    OrganizationalUnitIdentifier: orderer
